### ISSUE TITLE
Runtime error with latest geth

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#148]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x66b095]

goroutine 1 [running]:
panic(0xc27b20, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc42009fd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:781 +0x55
gopkg.in/urfave/cli%2ev1.GenericFlag.ApplyWithError.func1(0x0, 0x0)
        /home/splix/.go/src/gopkg.in/urfave/cli.v1/flag.go:128 +0xa4
gopkg.in/urfave/cli%2ev1.eachName(0x0, 0x0, 0xc420055b78)
        /home/splix/.go/src/gopkg.in/urfave/cli.v1/flag.go:94 +0xb5
gopkg.in/urfave/cli%2ev1.GenericFlag.ApplyWithError(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42009fd40, ...)
        /home/splix/.go/src/gopkg.in/urfave/cli.v1/flag.go:129 +0x1c7
github.com/ethereumproject/go-ethereum/cmd/utils.(*DirectoryFlag).ApplyWithError(0xc4203f4870, 0xc42009fd40, 0xc4203f4870, 0xc420055ca0)
        <autogenerated>:1 +0x6a
gopkg.in/urfave/cli%2ev1.flagSet(0x7ffe4485a2dd, 0x4, 0xc420453800, 0x46, 0x80, 0x4231ae, 0x800, 0x800)
        /home/splix/.go/src/gopkg.in/urfave/cli.v1/flag.go:80 +0x11b
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42006d520, 0xc42000c0a0, 0x5, 0x5, 0x0, 0x0)
        /home/splix/.go/src/gopkg.in/urfave/cli.v1/app.go:181 +0x177
main.main()
        /home/splix/.go/src/github.com/ethereumproject/go-ethereum/cmd/geth/main.go:241 +0x55
```

**Comment by pascaldekloe** [comment]
Dropping this nastly CLI framework is also on the bucket list. :angry: Which flags did you use @splix?

**Comment by splix** [comment]
`.go/bin/geth --datadir chains/geth-master-mainnet --port 30405`

**Comment by pascaldekloe** [comment]
Works for me @splix.

**Comment by splix** [comment]
Fails for me, even w/o any flag

**Comment by pascaldekloe** [comment]
That doesn't seem right. Even Travis can run the bats tests for cmd/geth.
https://travis-ci.org/ethereumproject/go-ethereum/builds/206830489

**Comment by pascaldekloe** [comment]
Also your line reference in main.go is off. Call app.Run is on line 238, not 241. It might be a Git issue.
https://github.com/ethereumproject/go-ethereum/blob/master/cmd/geth/main.go#L238
