### ISSUE TITLE
sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#259]
Happened on `CTRL-C` once for me while running normal sync:

```
I0603 16:08:30.913036 eth/downloader/downloader.go:984] imported 384 state entries in 537.063808ms: processed 183683, pending at least 170884
I0603 16:08:31.009622 core/blockchain.go:743] imported 237 receipt(s) (0 ignored) in 422.086445ms. #154368 [ba214c91… / 64002f77…]
I0603 16:08:31.309110 eth/downloader/downloader.go:984] imported 384 state entries in 135.999389ms: processed 184067, pending at least 170591
^CI0603 16:08:31.938049 eth/downloader/downloader.go:984] imported 384 state entries in 308.633247ms: processed 184451, pending at least 170213
I0603 16:08:31.938396 cmd/geth/cmd.go:72] Got interrupt, shutting down...
I0603 16:08:31.938584 node/node.go:327] IPC endpoint closed: /Users/ia/Desktop/geth_trials/mine-fast/mainnet/geth.ipc
I0603 16:08:32.256803 core/headerchain.go:309] imported 571 header(s) (0 ignored) in 856.419156ms. #164608 [93f28122… / c6c4c687…]
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 25535 [running]:
sync.(*WaitGroup).Wait(0xc42000a9c0)
	/usr/local/Cellar/go/1.8/libexec/src/sync/waitgroup.go:133 +0xd8
github.com/ethereumproject/go-ethereum/core.(*BlockChain).Stop(0xc42000a900)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/core/blockchain.go:566 +0x70
github.com/ethereumproject/go-ethereum/eth.(*Ethereum).Stop(0xc422fe2d80, 0xc4202d36e0, 0xc423412f58)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/backend.go:403 +0x33
github.com/ethereumproject/go-ethereum/node.(*Node).Stop(0xc4202dd180, 0x0, 0x0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/node/node.go:465 +0x21c
created by main.StartNode.func1
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/cmd/geth/cmd.go:73 +0x1a6
```

**Comment by whilei** [comment]
Same issue on ETHF https://github.com/ethereum/go-ethereum/issues/1816
