### ISSUE TITLE
Dump fails with out of memory

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#300]
```
$ geth dump 4083848 > d.json
I0713 20:08:23.482273 ethdb/database.go:63] Allotted 128MB cache and 1024 file handles to mainnet/chaindata
I0713 20:08:23.886791 core/blockchain.go:206] Last header: #4083848 [8cf629fe…] TD=77742348025724475597
I0713 20:08:23.886821 core/blockchain.go:207] Last block: #4083848 [8cf629fe…] TD=77742348025724475597
I0713 20:08:23.886831 core/blockchain.go:208] Fast block: #4083848 [8cf629fe…] TD=77742348025724475597
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf09324, 0x16)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc5f95d0000, 0x100000, 0x454c00, 0x17af5b8)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1796580, 0x100000, 0x7f6ebe2dd558)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:428 +0x374
runtime.(*mheap).grow(0x1796580, 0x1, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x1796580, 0x1, 0x7f6ebe2dd558)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x1796580, 0x1, 0x5, 0x7f6ed8a89000)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f6eda77bd58)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x1796580, 0x1, 0x10000000005, 0x4188dd)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mheap.go:628 +0xa0
runtime.(*mcentral).grow(0x1797ae0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcentral.go:212 +0x8e
runtime.(*mcentral).cacheSpan(0x1797ae0, 0x425cae)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcentral.go:93 +0x12a
runtime.(*mcache).refill(0x7f6ef9065770, 0x5, 0xc5f7b43400)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/mcache.go:122 +0xa0
runtime.(*mcache).nextFree.func1()
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:526 +0x32
runtime.systemstack(0xc439ac86c0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:281 fp=0xc42054ff48 sp=0xc42054ff40
runtime.(*mcache).nextFree(0x7f6ef9065770, 0xc420000105, 0xc420028000, 0xc420550010, 0xc420550060)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:527 +0xb9 fp=0xc42054ffa0 sp=0xc42054ff48
runtime.mallocgc(0x40, 0xe80700, 0xc420550001, 0x42ca9f)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:679 +0x827 fp=0xc420550040 sp=0xc42054ffa0
runtime.newobject(0xe80700, 0x203ffe)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/malloc.go:808 +0x38 fp=0xc420550070 sp=0xc420550040
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlock(0xc5f95749c0, 0x203ffe, 0x26df, 0xc5f9495101, 0x0, 0xc4203a6ab8, 0xc5f9561dc0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:612 +0xcc fp=0xc4205500f0 sp=0xc420550070
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlockCached.func1(0xc5f9561de0, 0xc42033d5c0, 0xc42298c000)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:626 +0x51 fp=0xc420550148 sp=0xc4205500f0
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/cache.(*Cache).Get(0xc42033d5c0, 0x338167, 0x203ffe, 0xc420550250, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/cache/cache.go:389 +0x208 fp=0xc4205501c0 sp=0xc420550148
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/cache.(*NamespaceGetter).Get(0xc5f95aa290, 0x203ffe, 0xc420550250, 0xc429e12408)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/cache/cache.go:58 +0x4b fp=0xc4205501f8 sp=0xc4205501c0
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).readBlockCached(0xc5f95749c0, 0x203ffe, 0x26df, 0xc422c00101, 0xc5f7bd7500, 0x904c08, 0xc4205502f0, 0xc4205502e8, 0xc422c081c0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:631 +0xed fp=0xc420550290 sp=0xc4205501f8
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).getIndexBlock(0xc5f95749c0, 0x1004701, 0xc5f95749c0, 0xc420028050, 0xc420028000, 0x8, 0x8)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:711 +0xc2 fp=0xc4205502e8 sp=0xc420550290
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).find(0xc5f95749c0, 0xc5f95b4bd0, 0x28, 0x28, 0xc420550401, 0x0, 0xc420550400, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:824 +0x137 fp=0xc4205503f8 sp=0xc4205502e8
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*Reader).Find(0xc5f95749c0, 0xc5f95b4bd0, 0x28, 0x28, 0x1, 0x0, 0xc420550528, 0x90de6f, 0xc42031f750, 0xc4205504f8, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table/reader.go:917 +0x7a fp=0xc420550480 sp=0xc4205503f8
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*tOps).find(0xc42031d650, 0xc421cee370, 0xc5f95b4bd0, 0x28, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.go:382 +0x19a fp=0xc420550508 sp=0xc420550480
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get.func1(0x4, 0xc421cee370, 0x20)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:176 +0x4e9 fp=0xc420550630 sp=0xc420550508
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).walkOverlapping(0xc454076370, 0x0, 0x0, 0x0, 0xc5f95b4bd0, 0x28, 0x28, 0xc4205507a0, 0xc420550770)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:125 +0x49f fp=0xc4205506f0 sp=0xc420550630
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*version).get(0xc454076370, 0x0, 0x0, 0x0, 0xc5f95b4bd0, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/version.go:230 +0x306 fp=0xc420550840 sp=0xc4205506f0
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).get(0xc42015c000, 0x0, 0x0, 0x0, 0x0, 0xc5f956f100, 0x20, 0x20, 0x1424efab, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:776 +0x245 fp=0xc420550960 sp=0xc420550840
github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).Get(0xc42015c000, 0xc5f956f100, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:842 +0x186 fp=0xc4205509f0 sp=0xc420550960
github.com/ethereumproject/go-ethereum/ethdb.(*LDBDatabase).Get(0xc42034a440, 0xc5f956f100, 0x20, 0x20, 0x58, 0xe71180, 0x16da900, 0xc5f956f720, 0x30)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/ethdb/database.go:93 +0x5a fp=0xc420550a50 sp=0xc4205509f0
github.com/ethereumproject/go-ethereum/trie.(*Trie).resolveHash(0xc420012c60, 0xc5f956f100, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/trie/trie.go:419 +0x70 fp=0xc420550b30 sp=0xc420550a50
github.com/ethereumproject/go-ethereum/trie.(*NodeIterator).step(0xc42001e780, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/trie/iterator.go:188 +0x8f9 fp=0xc420550dd8 sp=0xc420550b30
github.com/ethereumproject/go-ethereum/trie.(*NodeIterator).Next(0xc42001e780, 0x16b2e01)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/trie/iterator.go:116 +0x45 fp=0xc420550e60 sp=0xc420550dd8
github.com/ethereumproject/go-ethereum/trie.(*Iterator).Next(0xc42188d560, 0xc42279c6f0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/trie/iterator.go:45 +0x33 fp=0xc420550e90 sp=0xc420550e60
github.com/ethereumproject/go-ethereum/core/state.(*StateDB).RawDump(0xc4227b03c0, 0xc420551308, 0x0, 0x0, 0x9e1d4f, 0xed0560, 0xc4227b03c0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/state/dump.go:60 +0x105 fp=0xc4205511d8 sp=0xc420550e90
github.com/ethereumproject/go-ethereum/core/state.(*StateDB).Dump(0xc4227b03c0, 0xc420551308, 0x0, 0x0, 0x16dcd00, 0xc42034a440, 0xc4227b03c0)
```

**Comment by whilei** [comment]
This looks like a memory issue on the machine -- strange because [Travis docs](https://docs.travis-ci.com/user/ci-environment/) says they have 4-7.5GB memory, which should be more than enough.

Testing on my own computer with block 500000 I am able to get as high as 3.5% / 8GB RAM.

Are there any concurrent processes happening that may be limiting the available memory?

**Comment by splix** [comment]
I have:
```
$ free
             total       used       free     shared    buffers     cached
Mem:       8098868     117196    7981672       8580       3952      24012
```
I'll set to 16gb for that machine and will try again

**Comment by splix** [comment]
Same problem on 16Gb VM
```
$ free
             total       used       free     shared    buffers     cached
Mem:      16471088     555088   15916000       8580       5392     201080
```

**Comment by whilei** [comment]
Do other blocks have the same problem?

**Comment by splix** [comment]
I'm curious, how it's implemented? does it process block by block to get final dump?

**Comment by splix** [comment]
I've synced for more block and tried again. Failed anyway. 

Also, it takes a lot of time:
```
real    115m38.517s
user    53m13.020s
sys     14m53.116s
```

**Comment by splix** [comment]
`--cache=8192` didn't help, but failed much faster, just in 60 minutes

**Comment by whilei** [comment]
For a given block(s) it 
- gets the block from the chain by hash or hex
- creates a new state (`StateDB`) for that block
- iterates the state trie, for each address building an output-formattable account (`balance`, `nonce`, `code`, `storage`, etc)
- adds each account to a map, which is then formatted as JSON and printed

So it's got to parse every single account for a block, which takes a lot of memory (apparently!)

If you're looking for one or a few addresses in particular you can use the second argument for a list of comma-separated addresses to only include 
```
geth dump 4083848 0xasdfasdfasdfasdf,0xasdfasdfasdfasdf
```

**Comment by whilei** [comment]
Thinking more on this: It seems very -- either strange or a particular use-case -- to need to `dump` the entire "state of the world" for a given block height -- maybe we should consider dropping the command's _all-addresses_ feature and instead requiring a set of addresses to include. I guess it would be either that, or reconsider the kind of output generated -- a unified JSON format will cost a lot of memory and perhaps there are other, more streamable, alternatives. What do you think, @splix?
