### ISSUE TITLE
unimplemented: several debug api methods

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#364]
These should either be removed or implemented. 

I think the logging ones would be useful (`verbosity()`, `vmodule()`). Not sure about the other ones.

TODO:
- [x] figure out _exactly which_ methods aren't implemented
- [x] cut or implement each

```
~  ⟠ geth attach
Welcome to the Geth JavaScript console!

instance: Geth/source.v4.0.0+105-2a10671.master.17-10-11-08-24-57/darwin/go1.8
coinbase: 0xed0ab9153ab4f412b1a6c061b04d50ebaea7c10f
at block: 2456510 (Mon, 17 Oct 2016 16:47:20 PDT)
 datadir: /Users/ia/Library/EthereumClassic/mainnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> debug
{
  accountExist: function(),
  backtraceAt: function(),
  blockProfile: function(),
  chaindbProperty: function(),
  cpuProfile: function(),
  dumpBlock: function(),
  gcStats: function(),
  getBlockRlp: function(),
  goTrace: function(),
  memStats: function(),
  metrics: function(),
  printBlock: function(),
  seedHash: function(),
  setBlockProfileRate: function(),
  setHead: function(),
  stacks: function(),
  startCPUProfile: function(),
  startGoTrace: function(),
  stopCPUProfile: function(),
  stopGoTrace: function(),
  traceBlock: function(),
  traceBlockByFile: function(),
  traceBlockByHash: function(),
  traceBlockByNumber: function(),
  traceTransaction: function(),
  verbosity: function(),
  vmodule: function(),
  writeBlockProfile: function(),
  writeMemProfile: function()
}
> debug.verbosity(5)
Error: The method debug_verbosity does not exist/is not available
    at web3.js:3119:20
    at web3.js:6041:15
    at web3.js:5013:36
    at <anonymous>:1:1

> debug.vmodule('eth')
Error: The method debug_vmodule does not exist/is not available
    at web3.js:3119:20
    at web3.js:6041:15
    at web3.js:5013:36
    at <anonymous>:1:1

> debug.stacks()
Error: The method debug_stacks does not exist/is not available
    at web3.js:3119:20
    at web3.js:6041:15
    at web3.js:5013:36
    at <anonymous>:1:1

> debug.memStats();
Error: The method debug_memStats does not exist/is not available
    at web3.js:3119:20
    at web3.js:6041:15
    at web3.js:5013:36
    at <anonymous>:1:1
```

**Comment by khelle** [comment]
What about traceTransaction ? Its needed for detecting FAILED contract execution on the network, which I referenced in #407 . Is it not?
