### ISSUE TITLE
Suppress database error when exiting application

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#397]
Sometimes, after `Ctrl+C`, very verbose database error is logged, but actually it's nothing harmful (just some pending db operations after closing database).

The shutdown sequence should be altered to ensure that there are no write attempts to db after process interruption (SIGINT, Ctrl+C).

Example log (from @whilei):
```
I1031 12:35:06.944380 eth/downloader/downloader.go:988] imported 384 state entries in 65.502785ms: processed 42317, pending at least 216905
I1031 12:35:07.062240 core/blockchain.go:1225] imported 23 receipt(s) (0 ignored) in 26.313833ms. #26903 [e955c3d3… / 9caf64e8…]
I1031 12:35:07.131865 eth/downloader/downloader.go:988] imported 384 state entries in 95.352986ms: processed 42701, pending at least 216733
I1031 12:35:07.211957 eth/downloader/downloader.go:988] imported 384 state entries in 19.320258ms: processed 43085, pending at least 216603
I1031 12:35:07.239937 eth/downloader/downloader.go:988] imported 384 state entries in 37.059512ms: processed 43469, pending at least 216310
I1031 12:35:07.336335 eth/downloader/downloader.go:988] imported 384 state entries in 68.045377ms: processed 43853, pending at least 215886
I1031 12:35:07.500057 eth/downloader/downloader.go:988] imported 384 state entries in 76.269968ms: processed 44237, pending at least 215909
I1031 12:35:07.566072 core/headerchain.go:311] imported 1344 header(s) (0 ignored) in 604.514093ms. #29952 [86fe427f… / 8414d381…]
I1031 12:35:07.696206 eth/downloader/downloader.go:988] imported 384 state entries in 40.464318ms: processed 44621, pending at least 215964
I1031 12:35:07.802901 eth/downloader/downloader.go:988] imported 384 state entries in 143.921705ms: processed 45005, pending at least 215672
I1031 12:35:07.886313 core/blockchain.go:1225] imported 1705 receipt(s) (0 ignored) in 474.027029ms. #28608 [dea5aac2… / 92cd88c1…]
I1031 12:35:07.893952 eth/downloader/downloader.go:988] imported 384 state entries in 45.936064ms: processed 45389, pending at least 215198
I1031 12:35:07.895646 core/blockchain.go:1225] imported 11 receipt(s) (0 ignored) in 9.038837ms. #28619 [86fe427f… / 81c79141…]
^CI1031 12:35:08.041325 cmd/geth/cmd.go:86] Got interrupt, shutting down...
I1031 12:35:08.041373 node/node.go:382] HTTP endpoint closed: http://localhost:8545
I1031 12:35:08.041792 node/node.go:327] IPC endpoint closed: /Users/ia/Library/EthereumClassic/x1/geth.ipc
I1031 12:35:08.042154 core/blockchain.go:1046] Chain manager stopped
I1031 12:35:08.042170 eth/handler.go:219] Stopping ethereum protocol handler...
I1031 12:35:08.064093 eth/handler.go:240] Ethereum protocol handler stopped
I1031 12:35:08.064297 core/tx_pool.go:165] Transaction pool stopped
I1031 12:35:08.064423 eth/backend.go:483] Automatic pregeneration of ethash DAG: OFF (ethash dir: /Users/ia/.ethash)
F1031 12:35:08.064574 core/database_util.go:250] failed to store last header's hash into database: leveldb: closed
goroutine 2928 [running]:
github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc420347700, 0xc428cf6ea0, 0x73, 0xc2)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:826 +0xa7
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x5060cc0, 0xc400000003, 0xc4249211e0, 0x4f55ca2, 0x15, 0xfa, 0x0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:777 +0x348
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printfmt(0x5060cc0, 0xc400000003, 0x49776dc, 0x34, 0xc42bb895a8, 0x1, 0x1)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:715 +0x14f
github.com/ethereumproject/go-ethereum/logger/glog.Fatalf(0x49776dc, 0x34, 0xc42bb895a8, 0x1, 0x1)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1204 +0x67
github.com/ethereumproject/go-ethereum/core.WriteHeadHeaderHash(0x4f806a0, 0xc4206fa460, 0x7a5dc7dee84dcc1d, 0x1ad4ccb667b585ab, 0x13748a941b4512d3, 0x4793d440fd42a1f0, 0xcaf69d26634957d8, 0x751475c873c4b60a)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/core/database_util.go:250 +0x126
github.com/ethereumproject/go-ethereum/core.(*HeaderChain).SetCurrentHeader(0xc424925810, 0x0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/core/headerchain.go:405 +0xa0
github.com/ethereumproject/go-ethereum/core.(*BlockChain).Rollback(0xc4200ed200, 0xc42c546000, 0x800, 0x800)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/core/blockchain.go:1068 +0x690
github.com/ethereumproject/go-ethereum/core.(*BlockChain).Rollback-fm(0xc42c546000, 0x800, 0x800)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/handler.go:156 +0x48
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).processHeaders.func1(0xc42bb89c98, 0xc428360380, 0x487be2)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:1204 +0x40b
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).processHeaders(0xc428360380, 0x7501, 0xc42b8c2840, 0x4f73840, 0xc420460300)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:1230 +0x16f6
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0xae66c9b300000008, 0x4a06c10)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:470 +0x40
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync.func2(0xc42b8d8d80, 0xc428360380, 0xc42b98c240, 0xc42b9923a0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:499 +0x51
created by github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:504 +0x153
```

**Comment by whilei** [comment]
@tzdybal I can't remember if you wanted a full trace for this or not... maybe helpful?
 https://gist.github.com/e6f3b5b23e992d7a4692839f9082b376

**Comment by whilei** [comment]
here's another, even bigger one https://gist.github.com/whilei/55c811e191423a37d442fba2a2abad6c
