### ISSUE TITLE
log rotation: Fatal: no such file

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#435]
Branch: master

Rotation throws err from `compressOrphans` and `removeOld` for files which don't exist, and these errors are handled with `Fatal`.

```
I1214 07:59:08 SYNC Import ▶︎⟪# 173535 0x1322548…⟫ +⟪   0 blks    0 txs        0 mgas⟫ ✌︎︎︎⟪ 1/25 peers⟫
I1214 07:59:38 SYNC Import ▶︎⟪# 173535 0x1322548…⟫ +⟪   0 blks    0 txs        0 mgas⟫ ✌︎︎︎⟪ 1/25 peers⟫
F1214 08:00:01.315480 logger/glog/glog.go:1204] remove /Users/ia/Library/EthereumClassic/morden/log/geth.mh.ia.log.WARNING.20171206-115607.98452: no such file or directory
goroutine 7810 [running]:
github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc4204fc200, 0xc424e0f200, 0xb5, 0xfe)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1036 +0xcf
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x50bd720, 0xc400000003, 0xc421f0cb00, 0x4fb7184, 0x13, 0x4b4, 0x0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:987 +0x327
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printDepth(0x50bd720, 0xc400000003, 0x1, 0xc420044f70, 0x1, 0x1)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:916 +0x12a
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).print(0x50bd720, 0x3, 0xc420044f70, 0x1, 0x1)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:907 +0x5a
github.com/ethereumproject/go-ethereum/logger/glog.Fatal(0xc420044f70, 0x1, 0x1)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1754 +0x53
github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).rotateOld(0xc4204fc3c0, 0xbe84bed851c25126, 0x213c78e005, 0x50bcdc0)
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1204 +0x249
created by github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).Write
	/Users/ia/gocode/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1088 +0x1aa
F1214 08:00:01.317084 logger/glog/glog.go:1204] open /Users/ia/Library/EthereumClassic/morden/log/geth.mh.ia.log.ERROR.20171206-115607.98452: no such file or directory
```

Full traces:
[out.log](https://github.com/ethereumproject/go-ethereum/files/1559571/out.log)

**Comment by whilei** [comment]
Closed via #436
