### ISSUE TITLE
panic 

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#498]
Geth:
```
Geth Classic version: v4.2.0-c999068
Blockchain: Ethereum Classic Mainnet
```

Panic:
```
2018-02-06 12:38:07 Import    #5338809              0625efb9          1/ 0 txs/mgas         46/100 peers
2018-02-06 12:38:09 Import                                                                  46/100 peers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc4b23]

goroutine 124 [running]:
math/big.(*Int).Uint64(...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/types/block.go:326
github.com/ethereumproject/go-ethereum/core/types.(*Block).NumberU64(...)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/types/block.go:326
main.glob..func5(0xc423ba0000, 0xdf8475800, 0xc430bfa930, 0x64, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_display_basic.go:231 +0xed3
main.glob..func2(0xc4200e5cc0, 0xc423ba0000, 0xe8cd20, 0xc430bfa7e0, 0xdf8475800)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_display_basic.go:44 +0x17a
main.(*displayEventHandlers).runAllIfAny(0xc422c88b40, 0xc4200e5cc0, 0xc423ba0000, 0xe8cd20, 0xc430bfa7e0, 0xdf8475800, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_dispatch.go:93 +0xb7
main.runDisplayLogs.func2(0x191e2c0, 0xc422ceaf60, 0xc4200e5cc0, 0xc423ba0000, 0xdf8475800, 0xc422c88b40, 0xc422c78ea0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_dispatch.go:199 +0x233
created by main.runDisplayLogs
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_dispatch.go:194 +0x5ea
```

**Comment by whilei** [comment]
This was fixed in [4.2.2](https://github.com/ethereumproject/go-ethereum/releases/tag/v4.2.2)
