### ISSUE TITLE
cant cast: TxMsgreceive

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#541]
```
F0322 05:35:23.822426 eth/mlog.go:118] cant cast: TxMsgreceive                                            
goroutine 536706 [running]:                          
github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc4201cbc00, 0xc43266a800, 0x3f, 0xff)         
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1055 +0xcf          
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x1cf4e00, 0xc400000003, 0xc42050ac60, 0x199443c, 0xb, 0x76, 0x0)                                                                             
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1006 +0x32f         
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printDepth(0x1cf4e00, 0x3, 0x1, 0xc42726a978, 0x2, 0x2)                                                                                              
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:935 +0x12a          
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).print(0x1cf4e00, 0x3, 0xc42726a978, 0x2, 0x2)                                                                                                        
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:926 +0x5a           
github.com/ethereumproject/go-ethereum/logger/glog.Fatal(0xc42726a978, 0x2, 0x2)                          
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1779 +0x53          
github.com/ethereumproject/go-ethereum/eth.mlogWireDelegate(0xc43d0c0240, 0x1115ee8, 0x7, 0x2, 0xa66868, 0x0, 0x0, 0x1c28ae0, 0xc434cc5890)                                                                         
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/mlog.go:118 +0x13f1                 
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc420075e10, 0xc43d0c0240, 0x1c28ae0, 0xc434cc5890)                                                                                        
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:331 +0x5df2              
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).handle(0xc420075e10, 0xc43d0c0240, 0x0, 0x0)                                                                                                          
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:311 +0xb1f               
github.com/ethereumproject/go-ethereum/eth.NewProtocolManager.func1(0xc42523e340, 0x1c2ed20, 0xc4317241c0, 0x0, 0x0)                                                                                                
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:136 +0x1f2               
github.com/ethereumproject/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc4317241c0, 0xc42523e340)       
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/p2p/peer.go:308 +0x5d                   
created by github.com/ethereumproject/go-ethereum/p2p.(*Peer).startProtocols                              
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/p2p/peer.go:307 +0x1c8
```

**Comment by tzdybal** [comment]
Actual error on protocol level: `msg.Size > ProtocolMaxMsgSize` is true. Maybe we can use this to reproduce error in unit test.
