### ISSUE TITLE
GLOG rotation tests are not deterministic

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#564]
They sometimes fail on CI.

**Comment by whilei** [comment]
https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.1913#L419

```
F0516 19:38:42.971291 logger/glog/glog.go:1227] remove C:\Users\appveyor\AppData\Local\Temp\1\glog.test.exe.APPVYR-WIN.APPVYR-WIN_appveyor.log.INFO.20180516-193842.1234: The process cannot access the file because it is being used by another process.
goroutine 6 [running]:
github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc042054d00, 0xc0420dc000, 0xfa, 0x149)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1055 +0xd6
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x65c3e0, 0xc000000003, 0xc042260580, 0x64106b, 0x13, 0x4cb, 0x0)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1006 +0x323
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printDepth(0x65c3e0, 0xc000000003, 0x1, 0xc0421fff48, 0x1, 0x1)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:935 +0x130
github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).print(0x65c3e0, 0x3, 0xc0421fff48, 0x1, 0x1)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:926 +0x61
github.com/ethereumproject/go-ethereum/logger/glog.Fatal(0xc0421fff48, 0x1, 0x1)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1779 +0x5a
github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).rotateOld(0xc042054ec0, 0x3492ca64, 0xed28e7fc2, 0x65c200)
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1227 +0x2e1
created by github.com/ethereumproject/go-ethereum/logger/glog.(*syncBuffer).rotateOld
	c:/gopath/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1242 +0x4e7
FAIL	github.com/ethereumproject/go-ethereum/logger/glog	1.175s
?   	github.com/ethereumproject/go-ethereum/metrics	[no test files]
```

**Comment by tzdybal** [comment]
I hate Windows!
