### ISSUE TITLE
Segmentation Fault(SIGSEGV) when starting Geth

### ISSUE THREAD

**Issue by AyushG3112** [ethereumproject/go-ethereum#574]
Geth version: 1.8.6-stable
OS & Version: Ubuntu 16.04.2

#### Expected behaviour
Geth should start syncing the blockchain.

#### Actual behaviour
Geth crashes with segmentation violation

#### Steps to reproduce the behaviour
No specific steps. Simply starting Geth.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6faab]

goroutine 83 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc420662940)
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x2eb
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:113 +0x104
````

**Comment by shanejonas** [comment]
just to gather some more information: what version of `go` are you running?

**Comment by whilei** [comment]
@AyushG3112 looks like you're looking for https://github.com/ethereum/go-ethereum/issues
