### ISSUE TITLE
Crash on morden

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#585]
Happened today during morden sync:
```
Geth
Version: v5.2.1-42-gb634e470b
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Go OS: freebsd
Go Arch: amd64
Machine ID: 6a003b4a
GOPATH=
GOROOT=/usr/local/go
```

```geth --data-dir=~/geth --chain=morden --cache=128 --max-peers=75 --rpc --rpc-port 8546 --log-dir=~/geth/morden/logs --log-max-age=1w --log-total-max-size=1G --mlog=json --sputnikvm --display-fmt=green --port=40404 --mine --minerthreads=1```

```
panic: runtime error: invalid memory address or nil pointer dereference                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaa0fa7]                                    

goroutine 188627 [running]:                          
sync/atomic.(*Value).Load(...)                       
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/types/block.go:398                 
github.com/ethereumproject/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)                  
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/types/block.go:398 +0x67           
github.com/ethereumproject/go-ethereum/core.ApplyMultiVmTransaction(0xc420427b90, 0xc421808360, 0xc43418aaa0, 0xc42bec9700, 0xc42b1b98c0, 0xc42a789400, 0xc43418a940, 0x160, 0x150, 0x10aa560, ...)                 
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/multivm_processor.go:122 +0x20c2   
github.com/ethereumproject/go-ethereum/core.(*StateProcessor).Process(0xc4217d23c0, 0xc433af3b00, 0xc42bec9700, 0x54154a23db5020e, 0x862a8d08c2cd782f, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/state_processor.go:97 +0x45e       
github.com/ethereumproject/go-ethereum/core.(*BlockChain).InsertChain(0xc421808360, 0xc42c6e2000, 0x800, 0x800, 0x0, 0x0, 0x0)                                                                                      
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/blockchain.go:1573 +0x1ddc         
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).insertChain(0xc420130340, 0xc42c6e2000, 0x800, 0x800, 0x1cc40c0, 0x1cc40c0, 0xc43568d440)                                                             
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:181 +0x51                
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).(github.com/ethereumproject/go-ethereum/eth.insertChain)-fm(0xc42c6e2000, 0x800, 0x800, 0x0, 0x0, 0x0)                                                
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:158 +0x48                
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc42197c000, 0xc436c16000, 0x1800, 0x1800, 0x0, 0x0)                                                                        
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:1422 +0x17f
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc42197c000, 0xc428187798, 0x0)                                                                                         
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:1397 +0x74 
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).(github.com/ethereumproject/go-ethereum/eth/downloader.processFullSyncContent)-fm(0x8, 0x12205f0)                                               
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:550 +0x2a  
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc430c274e0, 0xc430caaae0, 0xc430bc1a20)                                                                                       
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:568 +0x51  
created by github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync                  
        /home/tomek/go/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:568 +0xc7
```

**Comment by tzdybal** [comment]
Error persist after restarts.

**Comment by tzdybal** [comment]
It seems that problem is not reproducible when SputnikVM is **not** in use.

**Comment by sorpaas** [comment]
Wrap this line (https://github.com/ethereumproject/go-ethereum/blob/master/core/multivm_processor.go#L122) with something that checks whether the block exists first. Like this function: https://github.com/ethereumproject/go-ethereum/blob/master/core/vm_env.go#L33

Don't know why blocks do not exist in this case. Might indicate a disk/database failure.
