### ISSUE TITLE
node key file loading can fatal with nil error

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#630]
> https://circleci.com/gh/ethereumproject/go-ethereum/3077?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```shell
not ok 86 should migrate datadir /Ethereum/ -> /EthereumClassic/ from ETC3.3 schema | --chain=mainnet
# (in test file tests/bats/migrate_datadir.bats, line 132)
#   `[ "$status" -eq 0 ]' failed
# I0613 07:52:26.695428 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/chaindata
# I0613 07:52:26.699417 cmd/geth/flag.go:762] --------------------------------------------------------------------------------------------------------------
# I0613 07:52:26.699438 cmd/geth/flag.go:763] Starting Geth Classic v3.3.0-1-gdd95f05
# I0613 07:52:26.699487 cmd/geth/flag.go:770] Loading blockchain: genesis block .
# I0613 07:52:26.699506 cmd/geth/flag.go:771] 4 blockchain hard-forks associated with this genesis block:
# I0613 07:52:26.699525 cmd/geth/flag.go:780]  1150000 Homestead hard-fork 
# I0613 07:52:26.699543 cmd/geth/flag.go:780]  1920000 ETF hard-fork resulted in a network split (support: false)
# I0613 07:52:26.699567 cmd/geth/flag.go:780]  2500000 GasReprice hard-fork 
# I0613 07:52:26.699580 cmd/geth/flag.go:780]  3000000 Diehard hard-fork 
# I0613 07:52:26.699594 cmd/geth/flag.go:786] Geth is configured to use the Ethereum (ETC) Classic blockchain!
# I0613 07:52:26.699617 cmd/geth/flag.go:788] --------------------------------------------------------------------------------------------------------------
# I0613 07:52:26.699906 cmd/geth/flag.go:552] WARNING: No etherbase set and no accounts found as default
# I0613 07:52:26.700790 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/chaindata
# I0613 07:52:26.720090 ethdb/database.go:63] Alloted 16MB cache and 16 file handles to /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/dapp
# I0613 07:52:26.723897 eth/backend.go:155] Protocol Versions: [63 62], Network Id: 1, Chain Id: 61
# I0613 07:52:26.723963 eth/backend.go:184] Blockchain DB Version: 3
# I0613 07:52:27.077653 eth/backend.go:230] WARNING: Wrote default ethereum genesis block
# I0613 07:52:27.077944 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
# I0613 07:52:27.077972 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
# I0613 07:52:27.077985 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
# I0613 07:52:27.078380 p2p/server.go:310] Starting Server
# I0613 07:52:28.797518 p2p/discover/udp.go:215] Listening, enode://0caa411dffc2caf89b210ab4dbe54e6a42d55c964750bf10298455f0dbd915a28cd49436b52508f278c72f05925b09f00e50f3b18ee034cb2253e6fdd39a8ba7@[::]:30303
# I0613 07:52:28.797716 p2p/server.go:553] Listening on [::]:30303
# I0613 07:52:28.800420 node/node.go:296] IPC endpoint opened: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/geth.ipc
# ReferenceError: 'exit' is not defined
#     at <anonymous>:1:1
# 
# I0613 07:52:28.916284 node/node.go:328] IPC endpoint closed: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/geth.ipc
# I0613 07:52:28.916312 core/blockchain.go:568] Chain manager stopped
# I0613 07:52:28.916320 eth/handler.go:219] Stopping ethereum protocol handler...
# I0613 07:52:28.916335 eth/handler.go:240] Ethereum protocol handler stopped
# I0613 07:52:28.916347 core/tx_pool.go:165] Transaction pool stopped
# I0613 07:52:28.916364 eth/backend.go:473] Automatic pregeneration of ethash DAG OFF (ethash dir: /Users/distiller/.ethash)
# I0613 07:52:29.034598 ethdb/database.go:78] Allotted 16MB cache and 16 file handles to /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/chaindata
# 2018-06-13 07:52:29 Allotted 16MB cache and 16 file handles to /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum/chaindata
# W0613 07:52:29.126451 cmd/geth/migrate_datadir.go:191] Found existing data directory named 'Ethereum' with default ETC chaindata.
# 		  	Moving it from: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/Ethereum, to: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/EthereumClassic
# 		  	To specify a different data directory use the '--datadir' flag.
# 2018-06-13 07:52:29 Geth Classic version: v5.4.2+3-08a5e61
# 2018-06-13 07:52:29 Blockchain: Ethereum Classic Mainnet
# 2018-06-13 07:52:29 Chain database: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp.RcKlMVc1/Library/EthereumClassic/mainnet/chaindata
# 2018-06-13 07:52:29 Blockchain upgrades configured: 6
# 2018-06-13 07:52:29  1150000 Homestead
# 2018-06-13 07:52:29  1920000 The DAO Hard Fork (0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f)
# 2018-06-13 07:52:29  2500000 GasReprice
# 2018-06-13 07:52:29  3000000 Diehard
# 2018-06-13 07:52:29  5000000 Gotham
# 2018-06-13 07:52:29  5900000 Defuse Difficulty Bomb
# 2018-06-13 07:52:29 Using 10 configured bootnodes
# 2018-06-13 07:52:29 Use Sputnik EVM: false
# 2018-06-13 07:52:29 No etherbase set and no accounts found as default
# F0613 07:52:29.129267 node/config.go:269] could not load key file: <nil>
# goroutine 1 [running]:
# github.com/ethereumproject/go-ethereum/logger/glog.stacks(0xc42005e700, 0xc4204f4000, 0x49, 0xee)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1055 +0xcf
# github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).output(0x56b1a40, 0xc400000003, 0xc4200a4580, 0x53fc3fc, 0xe, 0x10d, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1006 +0x32f
# github.com/ethereumproject/go-ethereum/logger/glog.(*loggingT).printfmt(0x56b1a40, 0x3, 0x4d2e920, 0x1b, 0xc421a75200, 0x1, 0x1)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:944 +0x14c
# github.com/ethereumproject/go-ethereum/logger/glog.Fatalf(0x4d2e920, 0x1b, 0xc421a75200, 0x1, 0x1)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/logger/glog/glog.go:1799 +0x67
# github.com/ethereumproject/go-ethereum/node.(*Config).NodeKey(0xc4200d57a0, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/node/config.go:269 +0x2cf
# github.com/ethereumproject/go-ethereum/node.New(0xc4200d57a0, 0xc42001c960, 0x24, 0xc4200a4370)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/node/node.go:104 +0x7c
# main.MakeSystemNode(0x4f16b00, 0x10, 0xc420198000, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/cmd/geth/flag.go:494 +0x14f
# main.localConsole(0xc420198000, 0x0, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/cmd/geth/consolecmd.go:82 +0x73
# reflect.Value.call(0x4bc3fe0, 0x4e09cc8, 0x13, 0x4d15e50, 0x4, 0xc421a75a80, 0x1, 0x1, 0xc421a75a00, 0x4cfa800, ...)
# 	/usr/local/Cellar/go/1.9.3/libexec/src/reflect/value.go:434 +0x905
# reflect.Value.Call(0x4bc3fe0, 0x4e09cc8, 0x13, 0xc421a75a80, 0x1, 0x1, 0xc420198000, 0x56b18c0, 0x0)
# 	/usr/local/Cellar/go/1.9.3/libexec/src/reflect/value.go:302 +0xa4
# github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x4bc3fe0, 0x4e09cc8, 0xc420198000, 0x0, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:480 +0x180
# github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x4d19b01, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4d40d9d, 0x30, 0x0, ...)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:186 +0x9ed
# github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42014c600, 0xc420010080, 0x8, 0x8, 0x0, 0x0)
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:236 +0x57d
# main.main()
# 	/Users/distiller/go/src/github.com/ethereumproject/go-ethereum/cmd/geth/main.go:336 +0x4f
```

**Comment by whilei** [comment]
resolved with #632
