### ISSUE TITLE
The method eth_subscribe_newHeads does not exist/is not available

### ISSUE THREAD

**Issue by feiyan-cs** [ethereumproject/go-ethereum#644]
Hello, I am scratching my head here, I am trying to integrate ETC with our exchange but I can't subscribe to newHeads or newPendingTransactions events. newHeads give me this error and newPendingTransactions mean while no error but no event is being triggered either.

I am using web3.js from https://github.com/ethereum/web3.js  and my ETC geth start cmd is 
geth --rpcapi "all" --ws --wsaddr "0.0.0.0" --wsport "8546" --wsorigins "*" --chain=morden --fast --port "30304"

**Comment by hao33828** [comment]
Could you specify which error newHeads event is throwing

**Comment by feiyan-cs** [comment]
`
Error: Returned error: The method eth_subscribe_newHeads does not exist/is not available
    at Object.ErrorResponse (/[MASKED]/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/[MASKED]/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /[MASKED]/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/[MASKED]/node_modules/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/[MASKED]/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) null Subscription {


`

**Comment by feiyan-cs** [comment]
```
Error: Returned error: The method eth_subscribe_newHeads does not exist/is not available
    at Object.ErrorResponse (/[MASKED]/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/[MASKED]/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /[MASKED]/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/[MASKED]/node_modules/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/[MASKED]/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /[MASKED]/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) null Subscription {

```

**Comment by feiyan-cs** [comment]
I am using the same code which is successful for ETH, but it doesn't work for ETC.

Am I missing anything? Not available on ETC?

**Comment by feiyan-cs** [comment]
Basically my code is using standard web3.js from https://github.com/ethereum/web3.js/

`web3.eth.subscribe('newBlockHeaders', function(){/...../})`

I am getting the same error when I call web3's 
`web3.eth.sendSignedTransaction`

**Comment by aarthiKannanEY** [comment]
Hi any resolution for this error? I am observing the same using dockerized geth with web3.

**Comment by gabmontes** [comment]
@whilei this is actually the response to a standard `newHeads` subscription attempt by web3 (`{"id": 1, "method": "eth_subscribe", "params": ["newHeads"]}`) which follows what is documented here too:

https://github.com/ethereumproject/go-ethereum/wiki/RPC-PUB-SUB#newheads

Is this actually implemented, despite it is documented in the wiki?
